system: "base16"
name: "Tokyo night"
author: "folke"
variant: "dark"
palette:
  base00: "24283b"
  base01: "1f2335"
  base02: "292e42"
  base03: "565f89"
  base04: "a9b1d6"
  base05: "c0caf5"
  base06: "c0caf5"
  base07: "ffffff"
  base08: "f7768e"
  base09: "ff9e64"
  base0A: "e0af68"
  base0B: "9ece6a"
  base0C: "1abc9c"
  base0D: "41a6b5"
  base0E: "bb9af7"
  base0F: "ff007c"

#5F69A0

  # base00: "1b1d2b"                                                                                                      
  # base01: "c7fb6d"                                                                                                      
  # base02: "ffd8ab"                                                                                                      
  # base03: "444a73"                                                                                                      
  # base04: "9ab8ff"                                                                                                      
  # base05: "828bb8"                                                                                                      
  # base06: "caabff"                                                                                                      
  # base07: "c8d3f5"                                                                                                      
  # base08: "ff757f"                                                                                                      
  # base09: "ff8d94"                                                                                                      
  # base0A: "ffc777"                                                                                                      
  # base0B: "c3e88d"                                                                                                      
  # base0C: "86e1fc"                                                                                                      
  # base0D: "82aaff"                                                                                                      
  # base0E: "c099ff"                                                                                                      
  # base0F: "b2ebff"  
